name: Linux Kernel Build

on:
  push:
    branches: master

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

      - name: Set up config
        run: make defconfig

      - name: Build kernel
        run: make -j$(nproc)

      - name: Upload bzImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel
          path: arch/x86/boot/bzImage
